// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw4SSOelDFHjAqXu5YsFuIwJSsXorYAs0',
    appId: '1:241477331154:web:a205797365ef40eed7250b',
    messagingSenderId: '241477331154',
    projectId: 'ebookapp-ff2a9',
    authDomain: 'ebookapp-ff2a9.firebaseapp.com',
    storageBucket: 'ebookapp-ff2a9.appspot.com',
    measurementId: 'G-QJ1H61DXEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKfYkiJsFiRUFfP4FeWpKIAK-xRaNB1e0',
    appId: '1:241477331154:android:2ca5883766dd3537d7250b',
    messagingSenderId: '241477331154',
    projectId: 'ebookapp-ff2a9',
    storageBucket: 'ebookapp-ff2a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGCeVwbEY8uql3DXMYNBDtgWX7T9GIeL8',
    appId: '1:241477331154:ios:f901cfa0f6a27f92d7250b',
    messagingSenderId: '241477331154',
    projectId: 'ebookapp-ff2a9',
    storageBucket: 'ebookapp-ff2a9.appspot.com',
    iosBundleId: 'com.example.ebookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGCeVwbEY8uql3DXMYNBDtgWX7T9GIeL8',
    appId: '1:241477331154:ios:f901cfa0f6a27f92d7250b',
    messagingSenderId: '241477331154',
    projectId: 'ebookapp-ff2a9',
    storageBucket: 'ebookapp-ff2a9.appspot.com',
    iosBundleId: 'com.example.ebookapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw4SSOelDFHjAqXu5YsFuIwJSsXorYAs0',
    appId: '1:241477331154:web:8b22165d7b1b5c9fd7250b',
    messagingSenderId: '241477331154',
    projectId: 'ebookapp-ff2a9',
    authDomain: 'ebookapp-ff2a9.firebaseapp.com',
    storageBucket: 'ebookapp-ff2a9.appspot.com',
    measurementId: 'G-JJJY1GC8DK',
  );
}
